#!/usr/bin/env node

var Jii = require('jii');
var mainConfig = require('./config/main');
var customConfig = require('./config');

require('jii/workers')
    .setEnvironment(customConfig.environment)
    .application(Jii.mergeConfigs(
        mainConfig,
        customConfig
    ));
