#!/usr/bin/env node

global.Jii = require('jii');

global.app = Jii.namespace('app');
require('./models/PackageItem')

var custom = require('./config');
require('jii-workers')
    .setEnvironment(custom.environment)
    .application(Jii.mergeConfigs(
        require('./config/main'),
        custom.main
    ));

